CoreStore2/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreStore2.Data;
using CoreStore2.Services;
using CoreStore2.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoreStore2.Controllers
{
    public class AppController : Controller
    {
        /* Using dependency injection here...
         * Note how we're requiring the IMailService in the constructor.
         * This will lask the service layer to figure out how to construct a
         * mailService, which requires a logger. The services layer will resolve 
         * dependencies of dependencies. The services layer knows which mailService
         * class to use due to services.AddTransient<IMailService, NullMailService>();
         * in ConfigureServices() in Startup.cs. AppController never has to understand 
         * the tree of dependencies, the registration in Startup.cs will do the heavy
         * lifting.
         */
        private readonly IMailService _mailService;
        private readonly ICoreStore2Repository _repository;

        //Using a constructor to inject the services we need
        public AppController(IMailService mailService, ICoreStore2Repository repository)
        {
            this._mailService = mailService;
            this._repository = repository;
        }

        public IActionResult Index()
        {

            return View();
        }

        //We can specify a route specific to contact:
        [HttpGet("contact")]
        public IActionResult Contact()
        {
            //ViewBag.Title = "Contact us"; //We can use viewbag in the controller, but we can also put them in  :)
            //throw new InvalidOperationException("Bad things happen."); //500 error.
            return View();
        }

        [HttpPost("contact")]
        public IActionResult Contact(ContactViewModel model) //Accepting payload from page, a ContactViewModel we created in /ViewModels.
        {
            if (ModelState.IsValid)
            {
                //Send the email
                _mailService.SendMessage("erik.martinessanches@gmail.com", model.Subject, $"From: {model.Name} - {model.Email}, Message: {model.Message}");
                ViewBag.UserMessage = "Mail sent.";
                ModelState.Clear(); //Clear the form.
            }
            return View();
        }

        [HttpGet("about")]
        public IActionResult About()
        {
            ViewBag.Title = "About us";
            return View();
        }

        [Authorize]
        public IActionResult Shop()
        {
            var results = _repository.GetAllProducts();
            return View(results);
        }
    }
}

CoreStore2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>CoreProject: @ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-inverse">
        <header class="container">
            <div class="navbar-header">
                <div class="navbar-brand"><i class="fa fa-paint-brush"></i>CoreStore2</div>
                <button class="navbar-toggle" data-toggle="collapse" data-target="#menu">&#9776;</button> <!--Hamburger button-->
            </div>
            <div id="menu" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="App" asp-action="Index">Home</a></li> <!--Using tag helpers for more robust links-->
                    <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
                    <li><a asp-controller="App" asp-action="About">About</a></li>
                    <li><a asp-controller="App" asp-action="Shop">Shop</a></li>
                </ul>
            </div>
        </header>
    </div>
    <section class="container">
        <h2 class="text-center">@ViewBag.Title</h2>
        @RenderBody()
    </section>
    <footer class="container"><div class="text-center">Copyright 2018 CoreStore2</div></footer>




    <script src="~/lib/jQuery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/index.js"></script>
    @*  If one of the pages creates a section called 'scripts', put it here in this layout, but it is not required.
        In this way we can put sections of a page that are emitted onto the Layout page somewhere else besides RenderBody().
        See Contact.cshtml for how to define a section called "scripts".*@
    @RenderSection("scripts", false) @*Not every page will need this.*@
</body>
</html>